name = "Rubin"
uuid = "2f670286-ad98-48a1-add4-def721795467"
authors = ["miguel raz <miguelraz@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
