using Rubin
using Tests
using Elliptic
using HypergeometricFunctions
using Polylogarithms
using SpecialFunctions

@test integrate(sec(c+d*x)^6*(A+C*sec(c+d*x)^2), x) == :(1//7*d^-1*(6C+7A)*tan(c+d*x)+1//21*d^-1*tan(c+d*x)^3*(12C+14A)+1//35*d^-1*tan(c+d*x)^5*(6C+7A)+1//7*C*d^-1*sec(c+d*x)^6*tan(c+d*x))
@test integrate(sec(c+d*x)^5*(A+C*sec(c+d*x)^2), x) == :(1//16*d^-1*(5C+6A)*arctanh(sin(c+d*x))+1//6*C*d^-1*sec(c+d*x)^5*tan(c+d*x)+1//16*d^-1*(5C+6A)*sec(c+d*x)*tan(c+d*x)+1//24*d^-1*sec(c+d*x)^3*(5C+6A)*tan(c+d*x))
@test integrate(sec(c+d*x)^4*(A+C*sec(c+d*x)^2), x) == :(1//5*d^-1*(4C+5A)*tan(c+d*x)+1//15*d^-1*tan(c+d*x)^3*(4C+5A)+1//5*C*d^-1*sec(c+d*x)^4*tan(c+d*x))
@test integrate(sec(c+d*x)^3*(A+C*sec(c+d*x)^2), x) == :(1//8*d^-1*(3C+4A)*arctanh(sin(c+d*x))+1//4*C*d^-1*sec(c+d*x)^3*tan(c+d*x)+1//8*d^-1*(3C+4A)*sec(c+d*x)*tan(c+d*x))
@test integrate(sec(c+d*x)^2*(A+C*sec(c+d*x)^2), x) == :(1//3*d^-1*(2C+3A)*tan(c+d*x)+1//3*C*d^-1*sec(c+d*x)^2*tan(c+d*x))
@test integrate((A+C*sec(c+d*x)^2)*sec(c+d*x), x) == :((1/2)*d^-1*(C+2A)*arctanh(sin(c+d*x))+(1/2)*C*d^-1*sec(c+d*x)*tan(c+d*x))
@test integrate(A+C*sec(c+d*x)^2, x) == :(A*x+C*d^-1*tan(c+d*x))
@test integrate((A+C*sec(c+d*x)^2)*cos(c+d*x), x) == :(A*d^-1*sin(c+d*x)+C*d^-1*arctanh(sin(c+d*x)))
@test integrate(cos(c+d*x)^2*(A+C*sec(c+d*x)^2), x) == :(x*(C+(1/2)*A)+(1/2)*A*d^-1*cos(c+d*x)*sin(c+d*x))
@test integrate(cos(c+d*x)^3*(A+C*sec(c+d*x)^2), x) == :(d^-1*(A+C)*sin(c+d*x)+-1//3*A*d^-1*sin(c+d*x)^3)
@test integrate(cos(c+d*x)^4*(A+C*sec(c+d*x)^2), x) == :(x*((1/2)*C+3//8*A)+1//4*A*d^-1*cos(c+d*x)^3*sin(c+d*x)+1//8*d^-1*(3A+4C)*cos(c+d*x)*sin(c+d*x))
@test integrate(cos(c+d*x)^5*(A+C*sec(c+d*x)^2), x) == :(d^-1*(A+C)*sin(c+d*x)+-1//3*d^-1*sin(c+d*x)^3*(C+2A)+1//5*A*d^-1*sin(c+d*x)^5)
@test integrate(cos(c+d*x)^6*(A+C*sec(c+d*x)^2), x) == :(x*(3//8*C+5//16*A)+1//6*A*d^-1*cos(c+d*x)^5*sin(c+d*x)+1//16*d^-1*(5A+6C)*cos(c+d*x)*sin(c+d*x)+1//24*d^-1*cos(c+d*x)^3*(5A+6C)*sin(c+d*x))
@test integrate(sec(c+d*x)^m*(C*sec(c+d*x)^2+-1*C*m*(1+m)^-1), x) == :(C*d^-1*(1+m)^-1*sec(c+d*x)^(1+m)*sin(c+d*x))
@test integrate(sec(c+d*x)^m*(A+-1*A*m^-1*sec(c+d*x)^2*(1+m)), x) == :(-1*A*d^-1*m^-1*sec(c+d*x)^(1+m)*sin(c+d*x))
@test integrate((b*sec(c+d*x))^5//2*(A+C*sec(c+d*x)^2), x) == :(2//7*C*d^-1*(b*sec(c+d*x))^5//2*tan(c+d*x)+2//21*b*d^-1*(b*sec(c+d*x))^3//2*(5C+7A)*sin(c+d*x)+2//21*b^2*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*(5C+7A)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^3//2*(A+C*sec(c+d*x)^2), x) == :(2//5*C*d^-1*(b*sec(c+d*x))^3//2*tan(c+d*x)+2//5*b*d^-1*(b*sec(c+d*x))^(1/2)*(3C+5A)*sin(c+d*x)+-2//5*b^2*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*(3C+5A)*Elliptic.E((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^(1/2)*(A+C*sec(c+d*x)^2), x) == :(2//3*C*d^-1*(b*sec(c+d*x))^(1/2)*tan(c+d*x)+1//3*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*(2C+6A)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-1//2*(A+C*sec(c+d*x)^2), x) == :(2*C*d^-1*(b*sec(c+d*x))^-1//2*tan(c+d*x)+d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*(-2C+2A)*Elliptic.E((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-3//2*(A+C*sec(c+d*x)^2), x) == :(2//3*A*d^-1*(b*sec(c+d*x))^-3//2*tan(c+d*x)+1//3*b^-2*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*(2A+6C)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-5//2*(A+C*sec(c+d*x)^2), x) == :(2//5*A*d^-1*(b*sec(c+d*x))^-5//2*tan(c+d*x)+1//5*b^-2*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*(6A+10C)*Elliptic.E((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-7//2*(A+C*sec(c+d*x)^2), x) == :(2//7*A*d^-1*(b*sec(c+d*x))^-7//2*tan(c+d*x)+1//21*b^-3*d^-1*(b*sec(c+d*x))^-1//2*(10A+14C)*sin(c+d*x)+1//21*b^-4*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*(10A+14C)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-9//2*(A+C*sec(c+d*x)^2), x) == :(2//9*A*d^-1*(b*sec(c+d*x))^-9//2*tan(c+d*x)+1//45*b^-3*d^-1*(b*sec(c+d*x))^-3//2*(14A+18C)*sin(c+d*x)+1//15*b^-4*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*(14A+18C)*Elliptic.E((1/2)*c+(1/2)*d*x,2))
@test integrate(sec(c+d*x)^-1//2*(3+3*sec(c+d*x)^2), x) == :(6*d^-1*sec(c+d*x)^(1/2)*sin(c+d*x))
@test integrate(sec(e+f*x)^m*(m+-1*sec(e+f*x)^2*(1+m)), x) == :(-1*f^-1*sec(e+f*x)^(1+m)*sin(e+f*x))
@test integrate(sec(e+f*x)^5*(5+-6*sec(e+f*x)^2), x) == :(-1*f^-1*sec(e+f*x)^5*tan(e+f*x))
@test integrate(sec(e+f*x)^4*(4+-5*sec(e+f*x)^2), x) == :(-1*f^-1*sec(e+f*x)^4*tan(e+f*x))
@test integrate(sec(e+f*x)^3*(3+-4*sec(e+f*x)^2), x) == :(-1*f^-1*sec(e+f*x)^3*tan(e+f*x))
@test integrate(sec(e+f*x)^2*(2+-3*sec(e+f*x)^2), x) == :(-1*f^-1*sec(e+f*x)^2*tan(e+f*x))
@test integrate((1+-2*sec(e+f*x)^2)*sec(e+f*x), x) == :(-1*f^-1*sec(e+f*x)*tan(e+f*x))
@test integrate(-1*sec(e+f*x)^2, x) == :(-1*f^-1*tan(e+f*x))
@test integrate(-1*cos(e+f*x), x) == :(-1*f^-1*sin(e+f*x))
@test integrate(cos(e+f*x)^2*(-2+sec(e+f*x)^2), x) == :(-1*f^-1*cos(e+f*x)*sin(e+f*x))
@test integrate(cos(e+f*x)^3*(-3+2*sec(e+f*x)^2), x) == :(-1*f^-1*cos(e+f*x)^2*sin(e+f*x))
@test integrate(cos(e+f*x)^4*(-4+3*sec(e+f*x)^2), x) == :(-1*f^-1*cos(e+f*x)^3*sin(e+f*x))
@test integrate(cos(e+f*x)^5*(-5+4*sec(e+f*x)^2), x) == :(-1*f^-1*cos(e+f*x)^4*sin(e+f*x))
@test integrate(sec(c+d*x)^3*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(B*d^-1*tan(c+d*x)+1//3*B*d^-1*tan(c+d*x)^3+3//8*C*d^-1*arctanh(sin(c+d*x))+1//4*C*d^-1*sec(c+d*x)^3*tan(c+d*x)+3//8*C*d^-1*sec(c+d*x)*tan(c+d*x))
@test integrate(sec(c+d*x)^2*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(C*d^-1*tan(c+d*x)+(1/2)*B*d^-1*arctanh(sin(c+d*x))+1//3*C*d^-1*tan(c+d*x)^3+(1/2)*B*d^-1*sec(c+d*x)*tan(c+d*x))
@test integrate((B*sec(c+d*x)+C*sec(c+d*x)^2)*sec(c+d*x), x) == :(B*d^-1*tan(c+d*x)+(1/2)*C*d^-1*arctanh(sin(c+d*x))+(1/2)*C*d^-1*sec(c+d*x)*tan(c+d*x))
@test integrate(B*sec(c+d*x)+C*sec(c+d*x)^2, x) == :(B*d^-1*arctanh(sin(c+d*x))+C*d^-1*tan(c+d*x))
@test integrate((B*sec(c+d*x)+C*sec(c+d*x)^2)*cos(c+d*x), x) == :(B*x+C*d^-1*arctanh(sin(c+d*x)))
@test integrate(cos(c+d*x)^2*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(C*x+B*d^-1*sin(c+d*x))
@test integrate(cos(c+d*x)^3*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :((1/2)*B*x+C*d^-1*sin(c+d*x)+(1/2)*B*d^-1*cos(c+d*x)*sin(c+d*x))
@test integrate(cos(c+d*x)^4*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :((1/2)*C*x+B*d^-1*sin(c+d*x)+-1//3*B*d^-1*sin(c+d*x)^3+(1/2)*C*d^-1*cos(c+d*x)*sin(c+d*x))
@test integrate(cos(c+d*x)^5*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(3//8*B*x+C*d^-1*sin(c+d*x)+-1//3*C*d^-1*sin(c+d*x)^3+1//4*B*d^-1*cos(c+d*x)^3*sin(c+d*x)+3//8*B*d^-1*cos(c+d*x)*sin(c+d*x))
@test integrate(cos(c+d*x)^6*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(3//8*C*x+B*d^-1*sin(c+d*x)+-2//3*B*d^-1*sin(c+d*x)^3+1//5*B*d^-1*sin(c+d*x)^5+1//4*C*d^-1*cos(c+d*x)^3*sin(c+d*x)+3//8*C*d^-1*cos(c+d*x)*sin(c+d*x))
@test integrate((b*sec(c+d*x))^3//2*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2//3*B*d^-1*(b*sec(c+d*x))^3//2*sin(c+d*x)+2//5*C*b^-1*d^-1*(b*sec(c+d*x))^5//2*sin(c+d*x)+6//5*C*b*d^-1*(b*sec(c+d*x))^(1/2)*sin(c+d*x)+-6//5*C*b^2*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*Elliptic.E((1/2)*c+(1/2)*d*x,2)+2//3*B*b*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^(1/2)*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2*B*d^-1*(b*sec(c+d*x))^(1/2)*sin(c+d*x)+2//3*C*b^-1*d^-1*(b*sec(c+d*x))^3//2*sin(c+d*x)+2//3*C*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*Elliptic.F((1/2)*c+(1/2)*d*x,2)+-2*B*b*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*Elliptic.E((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-1//2*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(-2*C*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*Elliptic.E((1/2)*c+(1/2)*d*x,2)+2*C*b^-1*d^-1*(b*sec(c+d*x))^(1/2)*sin(c+d*x)+2*B*b^-1*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-3//2*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2*B*b^-1*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*Elliptic.E((1/2)*c+(1/2)*d*x,2)+2*C*b^-2*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-5//2*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2//3*B*b^-2*d^-1*(b*sec(c+d*x))^-1//2*sin(c+d*x)+2*C*b^-2*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*Elliptic.E((1/2)*c+(1/2)*d*x,2)+2//3*B*b^-3*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-7//2*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2//3*C*b^-3*d^-1*(b*sec(c+d*x))^-1//2*sin(c+d*x)+2//5*B*b^-2*d^-1*(b*sec(c+d*x))^-3//2*sin(c+d*x)+2//3*C*b^-4*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*Elliptic.F((1/2)*c+(1/2)*d*x,2)+6//5*B*b^-3*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*Elliptic.E((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-9//2*(B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2//5*C*b^-3*d^-1*(b*sec(c+d*x))^-3//2*sin(c+d*x)+2//7*B*b^-2*d^-1*(b*sec(c+d*x))^-5//2*sin(c+d*x)+10//21*B*b^-4*d^-1*(b*sec(c+d*x))^-1//2*sin(c+d*x)+6//5*C*b^-4*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*Elliptic.E((1/2)*c+(1/2)*d*x,2)+10//21*B*b^-5*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate(sec(c+d*x)^4*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(1//5*d^-1*(4C+5A)*tan(c+d*x)+1//15*d^-1*tan(c+d*x)^3*(4C+5A)+3//8*B*d^-1*arctanh(sin(c+d*x))+1//4*B*d^-1*sec(c+d*x)^3*tan(c+d*x)+1//5*C*d^-1*sec(c+d*x)^4*tan(c+d*x)+3//8*B*d^-1*sec(c+d*x)*tan(c+d*x))
@test integrate(sec(c+d*x)^3*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(B*d^-1*tan(c+d*x)+1//3*B*d^-1*tan(c+d*x)^3+1//8*d^-1*(3C+4A)*arctanh(sin(c+d*x))+1//4*C*d^-1*sec(c+d*x)^3*tan(c+d*x)+1//8*d^-1*(3C+4A)*sec(c+d*x)*tan(c+d*x))
@test integrate(sec(c+d*x)^2*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :((1/2)*B*d^-1*arctanh(sin(c+d*x))+1//3*d^-1*(2C+3A)*tan(c+d*x)+(1/2)*B*d^-1*sec(c+d*x)*tan(c+d*x)+1//3*C*d^-1*sec(c+d*x)^2*tan(c+d*x))
@test integrate((A+B*sec(c+d*x)+C*sec(c+d*x)^2)*sec(c+d*x), x) == :(B*d^-1*tan(c+d*x)+(1/2)*d^-1*(C+2A)*arctanh(sin(c+d*x))+(1/2)*C*d^-1*sec(c+d*x)*tan(c+d*x))
@test integrate(A+B*sec(c+d*x)+C*sec(c+d*x)^2, x) == :(A*x+B*d^-1*arctanh(sin(c+d*x))+C*d^-1*tan(c+d*x))
@test integrate((A+B*sec(c+d*x)+C*sec(c+d*x)^2)*cos(c+d*x), x) == :(B*x+A*d^-1*sin(c+d*x)+C*d^-1*arctanh(sin(c+d*x)))
@test integrate(cos(c+d*x)^2*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(x*(C+(1/2)*A)+B*d^-1*sin(c+d*x)+(1/2)*A*d^-1*cos(c+d*x)*sin(c+d*x))
@test integrate(cos(c+d*x)^3*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :((1/2)*B*x+d^-1*(A+C)*sin(c+d*x)+-1//3*A*d^-1*sin(c+d*x)^3+(1/2)*B*d^-1*cos(c+d*x)*sin(c+d*x))
@test integrate(cos(c+d*x)^4*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(x*((1/2)*C+3//8*A)+B*d^-1*sin(c+d*x)+-1//3*B*d^-1*sin(c+d*x)^3+1//4*A*d^-1*cos(c+d*x)^3*sin(c+d*x)+1//8*d^-1*(3A+4C)*cos(c+d*x)*sin(c+d*x))
@test integrate(cos(c+d*x)^5*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(3//8*B*x+d^-1*(A+C)*sin(c+d*x)+-1//3*d^-1*sin(c+d*x)^3*(C+2A)+1//5*A*d^-1*sin(c+d*x)^5+1//4*B*d^-1*cos(c+d*x)^3*sin(c+d*x)+3//8*B*d^-1*cos(c+d*x)*sin(c+d*x))
@test integrate(cos(c+d*x)^6*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(x*(3//8*C+5//16*A)+B*d^-1*sin(c+d*x)+-2//3*B*d^-1*sin(c+d*x)^3+1//5*B*d^-1*sin(c+d*x)^5+1//6*A*d^-1*cos(c+d*x)^5*sin(c+d*x)+1//16*d^-1*(5A+6C)*cos(c+d*x)*sin(c+d*x)+1//24*d^-1*cos(c+d*x)^3*(5A+6C)*sin(c+d*x))
@test integrate((b*sec(c+d*x))^3//2*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2//3*B*d^-1*(b*sec(c+d*x))^3//2*sin(c+d*x)+2//5*C*d^-1*(b*sec(c+d*x))^3//2*tan(c+d*x)+2//5*b*d^-1*(b*sec(c+d*x))^(1/2)*(3C+5A)*sin(c+d*x)+-2//5*b^2*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*(3C+5A)*Elliptic.E((1/2)*c+(1/2)*d*x,2)+2//3*B*b*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^(1/2)*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2*B*d^-1*(b*sec(c+d*x))^(1/2)*sin(c+d*x)+2//3*C*d^-1*(b*sec(c+d*x))^(1/2)*tan(c+d*x)+1//3*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*(2C+6A)*Elliptic.F((1/2)*c+(1/2)*d*x,2)+-2*B*b*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*Elliptic.E((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-1//2*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2*C*d^-1*(b*sec(c+d*x))^-1//2*tan(c+d*x)+d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*(-2C+2A)*Elliptic.E((1/2)*c+(1/2)*d*x,2)+2*B*b^-1*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-3//2*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2//3*A*d^-1*(b*sec(c+d*x))^-3//2*tan(c+d*x)+2*B*b^-1*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*Elliptic.E((1/2)*c+(1/2)*d*x,2)+1//3*b^-2*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*(2A+6C)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-5//2*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2//5*A*d^-1*(b*sec(c+d*x))^-5//2*tan(c+d*x)+2//3*B*b^-2*d^-1*(b*sec(c+d*x))^-1//2*sin(c+d*x)+1//5*b^-2*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*(6A+10C)*Elliptic.E((1/2)*c+(1/2)*d*x,2)+2//3*B*b^-3*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*Elliptic.F((1/2)*c+(1/2)*d*x,2))
@test integrate((b*sec(c+d*x))^-7//2*(A+B*sec(c+d*x)+C*sec(c+d*x)^2), x) == :(2//7*A*d^-1*(b*sec(c+d*x))^-7//2*tan(c+d*x)+1//21*b^-3*d^-1*(b*sec(c+d*x))^-1//2*(10A+14C)*sin(c+d*x)+2//5*B*b^-2*d^-1*(b*sec(c+d*x))^-3//2*sin(c+d*x)+1//21*b^-4*d^-1*(b*sec(c+d*x))^(1/2)*cos(c+d*x)^(1/2)*(10A+14C)*Elliptic.F((1/2)*c+(1/2)*d*x,2)+6//5*B*b^-3*d^-1*(b*sec(c+d*x))^-1//2*cos(c+d*x)^-1//2*Elliptic.E((1/2)*c+(1/2)*d*x,2))
