using Rubin
using Tests
using Elliptic
using HypergeometricFunctions
using Polylogarithms
using SpecialFunctions

@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-3//2*(A+C*sin(e+f*x)^2), x) == :(1//4*a^-1*f^-1*(a+a*sin(e+f*x))^(1/2)*(c+-1*c*sin(e+f*x))^-3//2*(A+C)*cos(e+f*x)+-1//4*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*(A+-3C)*cos(e+f*x)*log(1+-1*sin(e+f*x))+1//4*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*(A+C)*cos(e+f*x)*log(1+sin(e+f*x)))
@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-3//2*(A+B*sin(e+f*x)+C*sin(e+f*x)^2), x) == :(1//4*a^-1*f^-1*(a+a*sin(e+f*x))^(1/2)*(c+-1*c*sin(e+f*x))^-3//2*(A+B+C)*cos(e+f*x)+-1//4*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*(A+-1B+-3C)*cos(e+f*x)*log(1+-1*sin(e+f*x))+1//4*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*(A+C+-1B)*cos(e+f*x)*log(1+sin(e+f*x)))
@test integrate(sin(e+f*x)^-3//2*(a+b*sin(e+f*x))*(A+B*sin(e+f*x)+C*sin(e+f*x)^2), x) == :(f^-1*(-2*a*(A+-1C)+2*B*b)*Elliptic.E((1/2)*e+-1//4*pi+(1/2)*f*x,2)+1//3*f^-1*(2*C*b+6*A*b+6*B*a)*Elliptic.F((1/2)*e+-1//4*pi+(1/2)*f*x,2)+-2*A*a*f^-1*sin(e+f*x)^-1//2*cos(e+f*x)+-2//3*C*b*f^-1*sin(e+f*x)^(1/2)*cos(e+f*x))
@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*sin(e+f*x)^3, x) == :((1/2)*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cos(e+f*x)^3+-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cos(e+f*x)*log(cos(e+f*x)))
@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*sin(e+f*x), x) == :(-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cos(e+f*x)*log(cos(e+f*x)))
@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*csc(e+f*x), x) == :(f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cos(e+f*x)*log(tan(e+f*x)))
@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*csc(e+f*x)^2, x) == :(-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cot(e+f*x)+f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*arctanh(sin(e+f*x))*cos(e+f*x))
@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*csc(e+f*x)^3, x) == :(f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cos(e+f*x)*log(tan(e+f*x))+-1//2*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cot(e+f*x)^2*cos(e+f*x))
@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*csc(e+f*x)^4, x) == :(-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cot(e+f*x)+f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*arctanh(sin(e+f*x))*cos(e+f*x)+-1//3*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*csc(e+f*x)^2*cot(e+f*x))
@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-3//2*sin(e+f*x)^3, x) == :(c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cos(e+f*x)*log(cos(e+f*x))+(1/2)*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*sin(e+f*x)^2*tan(e+f*x)+(1/2)*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*sin(e+f*x)*tan(e+f*x)+-3//2*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*arctanh(sin(e+f*x))*cos(e+f*x)+3//2*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cos(e+f*x)*sin(e+f*x))
@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-3//2*csc(e+f*x), x) == :((1/2)*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*tan(e+f*x)+c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cos(e+f*x)*log(tan(e+f*x))+(1/2)*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*arctanh(sin(e+f*x))*cos(e+f*x)+(1/2)*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*sin(e+f*x)*tan(e+f*x))
@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-3//2*csc(e+f*x)^2, x) == :(-3//2*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cot(e+f*x)+c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cos(e+f*x)*log(tan(e+f*x))+(1/2)*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*csc(e+f*x)*sec(e+f*x)+(1/2)*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*sin(e+f*x)*tan(e+f*x)+3//2*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*arctanh(sin(e+f*x))*cos(e+f*x))
@test integrate((a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-3//2*csc(e+f*x)^3, x) == :(-3//2*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cot(e+f*x)+(1/2)*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*csc(e+f*x)*sec(e+f*x)+(1/2)*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*sin(e+f*x)*tan(e+f*x)+2*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cos(e+f*x)*log(tan(e+f*x))+-1//2*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*cot(e+f*x)^2*cos(e+f*x)+3//2*c^-1*f^-1*(a+a*sin(e+f*x))^-1//2*(c+-1*c*sin(e+f*x))^-1//2*arctanh(sin(e+f*x))*cos(e+f*x))
